pickstore/config/routes.rb
Pickstore::Application.routes.draw do
  resources :albums do
  	resources :images, :only => ['show', 'destroy']
  end
  resources :images, :only => ['show', 'destroy']
  
  resources :users, :only => ['new', 'create']
  	
	resources :logins, :only => ['index', 'login', 'logout'] do
		post 'login', :on => :collection
	end

	match 'logout' => 'logins#logout'

  root :to => 'logins#index'
  

end

pickstore/app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :user_id, :images_attributes, :tags_attributes
  
  belongs_to :user
  has_many :images, :dependent => :destroy
  
  validates :name, :presence => true
  
  accepts_nested_attributes_for :images, 
  :reject_if => proc { |attrs| attrs['title'].blank? }, :allow_destroy => true
end

pickstore/app/models/image.rb
class Image < ActiveRecord::Base  
  attr_accessible :picture_content_type, :picture_file_name, :picture_file_size, :title, :album_id, :picture, :tags_attributes

  belongs_to :album
  
  has_and_belongs_to_many :tags
      
  has_attached_file :picture, :styles => {:thumb => "100*100#", :small => "150*150>"}, 
  		:path => ":rails_root/public/system/:attachment/:id/:style/:filename", :url => "/system/:attachment/:id/:style/:filename",
  		:whiny_thumbnails => true
  		
  validates :title, :presence => true
  
  #Fixed: NG
  validates_format_of :picture_file_name, :with => %r{\.(jpeg|gif)$}i
  validates_attachment_size :picture, :less_than => 1.megabytes
  validates_attachment_presence :picture
  
  accepts_nested_attributes_for :tags, 
  :reject_if => proc { |attrs| attrs['name'].blank? }, :allow_destroy => true
end

pickstore/app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessible :name

  has_and_belongs_to_many :images
end

pickstore/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username, :password_confirmation
  
	# Fixed: NG
	has_secure_password
  validates :username, :presence => true, :uniqueness => true
  
  #Fixed: NG
  validates :password, :length => {:minimum => 5}
	  										 
  has_many :albums
 end

pickstore/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_filter :only_when_user_is_logged_in
	
  def index
    @albums = @current_user.albums.to_a

    # Fixed: NG
    respond_to do |format|
      format.html
      format.json { render json: @albums }
    end
  end

  def show
    # Optimized: NG

    # Optimized: NG
		begin
    	@album = @current_user.albums.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to albums_path and return
		end
		
		respond_to do |format|
			format.html
		end
  end

  def new
    @album = Album.new

    respond_to do |format|
      format.html
      format.json { render json: @album }
    end
  end

  def edit
    # Fixed: NG
  	#@user = User.find(session[:current_user_id])
  	
    # Optimized: NG
    begin
    	@album = @current_user.albums.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to albums_path
		end
  end

  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        # -> Optimized: NG
        format.json { head :ok, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #Fixed: NG
    begin
	    @album = Album.find(params[:id])
 		rescue ActiveRecord::RecordNotFound
			redirect_to albums_path and return
		end

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    #Fixed: NG
    begin
	    @album = Album.find(params[:id])
 		rescue ActiveRecord::RecordNotFound
			redirect_to albums_path and return
		end

    @album.destroy
   	redirect_to albums_path and return :notice => "Album was not destroyed!" if !@album.destroyed?

    respond_to do |format|
      format.html { redirect_to albums_url }
    end
  end
end

pickstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
	  
	def current_user
    # Optimized: NG
    # FIXME: WA: current_user below is an local variable.
    # It will cease to exist as soon as the method finishes.
    # Use an instance variable instead.
    #Fixed: NG
		@current_user ||= User.find(session[:current_user_id])
	end
	
  # REFACTOR: WA: You need not define following method
  # in application controller. Define it in the controller
  # where you need it.
  
  #Refactored: NG
 
  private
  
		def only_when_user_is_logged_in
			redirect_to logins_path if !User.find_by_username(session[:current_user])
		end
end

pickstore/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # Fixed: NG
 	before_filter :only_when_user_is_logged_in, :fetch_image
  def show  
    # Refactored: NG
      
    respond_to do |format|
	    format.html
	  end
  end

  def destroy
    # Refactored: NG

	  @image.destroy		  
		redirect_to albums_path, :notice => "Image was not destroyed!" if !@image.destroyed?

    respond_to do |format|
      format.html { redirect_to albums_path }
    end
  end
end

def fetch_image
	begin
		@image ||= @current_user.albums.find(params[:album_id]).images.find(params[:id])
    #	FIXME: WA: Following will fetch any image for display, destruction.
    #	Not neccessarily current user's.
		#@image ||= Image.find(params[:id])
		#Fixed: NG
	rescue ActiveRecord::RecordNotFound
		redirect_to album_path(current_album) and return
	end
end

pickstore/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	before_filter :only_when_user_is_logged_in, :only => :logout

	def index
		respond_to do |format|
      format.html      
    end
  end
  
 	def login
		respond_to do |format|
			user = User.find_by_username(params[:username])
			if user && user.authenticate(params[:password])
				session[:current_user] = user.username
				session[:current_user_id] = user.id
				flash[:notice] = "You have logged in successfully!"
				format.html { redirect_to albums_path }
			else
				format.html { redirect_to logins_path, notice: 'username or password is incorrect!'}
			end
		end
	end
	
	def logout
		session[:current_user_id] = nil
		session[:current_user] = nil
		redirect_to logins_path
	end
end

pickstore/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new

    respond_to do |format|
      format.html
    end
  end
		
	def create
	  @user = User.new(params[:user])

	  respond_to do |format|
	    if @user.save
	    	session[:current_user] = @user.username
	    	session[:current_user_id] = @user.id
	      format.html { redirect_to albums_path, notice: 'You are successfully registered!' }
	    else
	      format.html { render :action => "new" }
	    end
	  end
	end
end

pickstore/app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object) do |builder|
			render(association.to_s + "/form", :f => builder)
		end
		link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
	end
end

pickstore/app/helpers/images_helper.rb
module ImagesHelper
end

pickstore/app/views/albums/_form.html.erb
<% image = @album.images.build %>
<% image.tags.build %>
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id, :readonly => true, :value => session[:current_user_id] %>
  </div>
  
  <div class = "nested_img">
	 	<h2>Images</h2>
		<%= f.fields_for :images do |builder| %>
			<%= render "images/form", :f => builder %>
		<% end %>
		<p><%= link_to_add_fields "More images", f, :images %></p>
	</div>
	  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pickstore/app/views/albums/_image_form.html.erb
<%= f.fields_for :images do |builder| %>
  <%= render "images/form", :f => builder %>
<% end %>
</div>
	
<div class="actions">
	<%= f.submit ('Add Image') %>
</div>

pickstore/app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

pickstore/app/views/albums/index.html.erb
<div class = "albumListing">

<div id = "user">
	<table>
		<tr>
      <%# FIXME: WA: Avoid using session variable directly
      Although it seems innocuous, using values from
      your database will make much sense. Think about a
      situation in which you have stale username in your
      session. #%>
      <%#Fixed: NG%>
			<td>Hi <b><%= @current_user.username %> </b></td>
      <%# FIXME: WA: Following is a makes a GET request
      while _changing_ the server state. Make it POST.
      Or better yet DELETE because it actually DELETEs
      something from server. in this case user's session %>
      <%# Fixed: NG%>
			<td><%= link_to "Logout", logout_path, :method => :delete %></td>
		</tr>
	</table>
</div>

	<br />

	<div><h1>Listing Albums</h1></div>
	
	<table>
		<tr class = "headers">
		  <th class = "first">Name</th>
		  <th></th>
		  <th></th>
		  <th></th>
		</tr>
		
  <%# FIXME: WA: Populate albums in an instance variable in controller's action
        and use it here. The render json: @albums will also use the same variable.
        This way your code is DRY.
        
        #Fixed: NG
  #%>
	<% @albums.each do |album| %>
		<tr class = "albums">
		  <td class = "first"><%= album.name %></td>
      <%# OPTIMIZE: WA: You already have a album's user in current_user.
      Utilize that to show user name here. I'm assuming that you are
      showing only current user's albums to current user. It makes excess
      SQL queries. %>
      <%# Optimized: NG%>

		  <td class = "link"><%= link_to 'Show', album %></td>
			<td class = "link"><%= link_to 'Edit', edit_album_path(album) %></td>
			<td class = "link"><%= link_to 'Destroy', album, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
	<% end %>

	</table>

	<br />
	<%= link_to 'New Album', new_album_path %>
</div>

pickstore/app/views/albums/new.html.erb
<div class = "newAlbum">
	<h1>New album</h1>

	<%= render 'form' %>

	<%= link_to 'Back', albums_path %>
</div>

pickstore/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<table id = "alb_usr">
	<tr>
		<td><b>Album:</b> <%= @album.name %></td>
	</tr>
</table>

<div><h1>Images</h1></div>

<div>
	<table class = "images_table">
		<tr id = "headers">
			<th id = "first">Title</td>
			<th>Image</td>
			<th></th>	
			<th></th>
		</tr>			
	<% @album.images.each do |image| %> 
		<tr class = "images_row">
			<td class = "first"><%= image.title %></td>
			<td><%= image_tag image.picture.url(:thumb) %></td>
      <%# FIXME: WA: Following two links are used to 'show' and 'destroy'
      a single image. There is no need to create a URI like /albums/:id/image/:image_id.
      A URI like /images/:id will suffice. 
      # Fixed: NG
      %>
			<td class = "link"><%= link_to "show",  image %></td>
			<td class = "link"><%= link_to "destroy", image, confirm: 'Are you sure!', method: :delete %></td>
		</tr>
	<% end %>
	</table>
	<br />
 </div>
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

pickstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pickstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class = "header">
		<div class = "headText">
			<span class = "title">pickstore</span>
		</div>
	</div>
	<div class = "wrapper">
		<div class = "contentWrapper">
			<%= yield %>
		</div>
	</div>
	
</body>
</html>

pickstore/app/views/logins/_form.html.erb
<div class = "signIn">
	<%= form_tag :action => "login" do %>
		<p><%= notice %></p>
		<table id = "login">
			<tr>
				<td id = "username"><%=  label_tag(:username, "Username:")  %></td>
				<td><%=  text_field_tag(:username) %></td>
			</tr>
			<tr>
				<td id = "password"><%=  label_tag(:password, "Password:")  %></td>
				<td><%=  password_field_tag(:password) %></td>
			</tr>
			<tr id = "submit">
				<td id = "submit"> <%= submit_tag("Submit") %> </td>
				<td id = "signUpLink"> <%= link_to "Sign Up", new_user_path %> </td>
			</tr>
		</table>
		<br />		
		
	<% end %>
</div>

pickstore/app/views/logins/index.html.erb
<br /> <br /> <br /> <br /> <br />

<div class = "images">
	<%= image_tag "download.jpg", :id => "img1" %>
	<%= image_tag "images (1).jpg", :id => "img2" %>
	<br />
	<%= image_tag "images (2).jpg", :id => "img3" %>
</div>

<div class = login>
	<div class = head> Login </div><hr />
	<%= render "form" %>
</div>