twitter/config/routes.rb
Twitter::Application.routes.draw do

	resources :logins, :only => ['index', 'login', 'logout'] do
		post :login, :on => :collection
	end
	
	resources :users, :only => ['new', 'create', 'show']
	
	resources :tweets, :except => ['edit', 'update', 'show'] do
		get :mine, :on => :collection
	end
		
	resources :tweets_users, :only => ['create', 'destroy']
	
	match 'logout' => 'logins#logout'
	match 'login' => 'logins#index'
	
	resources :follows, :only => ['index', 'create', 'destroy']
	
	match "whoToFollow" => 'follows#index'	

  root :to => 'logins#index'

end

twitter/app/models/tweet.rb
# TODO: WA: This model does not have any tests.
class Tweet < ActiveRecord::Base
	include UsersHelper
  attr_accessible :message, :ttype, :user_id
  
  has_many :tweets_users, :dependent => :destroy
  has_many :users, :through => :tweets_users
  belongs_to :user
  
  validates :message, :length => {:maximum => 160}
  # Fixed :NG I was also managing this with javascript. Do we really need to manage here?
  # WA: Yes we do. Consider a situation where you are exposing your application
  # to outer world as a web service. You may or may not be able to control the
  # clients that make request to your application. In that case this validation
  # will make sure that our database is consistent. Moreover, if you try to create
  # a tweet from console, this will make sure you do not put incosistent data in
  # your db. Please remove this comment after reading.
  
 	def find_if_retweeted(uid)
		TweetsUser.find(:first, :conditions => ['user_id = ? and tweet_id = ?', uid, self.id])
	end
end

twitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # TODO: WA: Test this controller more thoroughly.
	before_filter :only_when_user_is_logged_in
	
	def index
		@tweet = current_user.tweets.new
		@followings = current_user.followings.count
		@followers = current_user.inverse_followings.count
		@tweet_user = TweetsUser.new
		
    # OPTIMIZE: WA: Sort the results in SQL itself. Using ruby's sort
    # is very inefficient.
    #
    # REFACTOR: Move following SQL find to Tweet model in its own method
    # and write tests for it.
		@tweets = Tweet.find_by_sql("select tweets.* from tweets where user_id = #{current_user.id} UNION select tweets.* from tweets_users INNER JOIN follows ON tweets_users.user_id = following_id INNER JOIN tweets ON tweets_users.tweet_id = tweets.id where follows.user_id = #{current_user.id} UNION select tweets.* from tweets INNER JOIN follows ON tweets.user_id = follows.following_id where follows.user_id = #{current_user.id} UNION select * from tweets where ttype = 'public'").sort.reverse
				
		respond_to do |format|
			format.html
		end
	end

	def create
	  @tweet = current_user.tweets.build(params[:tweet])

		respond_to do |format|
		  if @tweet.save
		    format.html { redirect_to tweets_path, notice: 'Tweet was successfully posted.' }
		  else
		  	render :text => "Tweet was not saved successfully!"
		  end
		end
	end
	
  # TODO: WA: Write thorough tests for following action
	def destroy
		begin
			@tweet = current_user.tweets.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			render :text => "Record Not Found"
		end
		
		render :text => "Tweet was not deleted!" and return if !@tweet.destroy
		respond_to do |format|		
			format.html { redirect_to tweets_path }
		end
	end
	
	def mine
		
		respond_to do |format|
			format.html
		end
	end
end	

twitter/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
	<table>
		<tr>
			<td colsapan = "2"><%= f.text_area :message, :rows => 2 %></td>
		</tr>
		
    <%# REFACTOR: WA: Move following logic in if statement to User model %>
    <%# Refactored: NG: I have moved it to application controller as finding current_user uses session which is undefined in models. %>
    <%# WA: You can create a method like User#public_user? and in there self.username.eql? "public_user" %>

		<% if public_user? %>
   		<%= f.hidden_field :ttype, :value => "public" %>
		<% else %>
			<%= f.hidden_field :ttype, :value => "private" %>
		<% end %>
				
		<tr>
			<td id = "charCount"><span id = "count"><b></b></span><span id = "button"><%= f.submit('Tweet', :class => 'tweetSubmit') %></td>
		</tr>
	</table>
<% end %>

twitter/app/views/tweets/index.html.erb
<div class = "tweetsContentWrapper">
	<div class = "tweetsContent">
		<div id = "user">
			<span><%= link_to "Logout", logout_path, method: :delete %></span>
		</div>
		
		<div class = dashboard>
			<div class = "composeTweets">
				<div class = profileName>
					<b><%= link_to current_user.fullname, user_path(current_user) %></b>
					<div id = "sview">
						<span> view my profile page</span>
					</div>
				</div>
				<div class = "status">
					<ul class = "status">
						<li><b><%= my_tweets.count %></b><div><%= link_to "Tweets", mine_tweets_path %></div></li>
						<li><b><%= @followings %></b><div><%= link_to "Following" %></div></li>
						<li id = "last"><b><%= @followers %></b><div><%= link_to "Followers" %></div></li>
					</ul>
				</div>
				
				<div class = "form">
					<%= render "form" %>
				</div>
			</div>
			
			<div class = "whoToFollow">
				<div><span>Who to follow</span></div>
				<div><%= link_to "follow here", whoToFollow_path %></div>
			</div>
		</div>
		
		<div class = tweets>
			<div class = "tweetsTable">
				<table>
					<tr>
						<th> Tweets </th>
					</tr>																			
					
					<% @tweets.each do |tweet| %>
						<tr>
							<td>
		            <%# FIXME: WA: We already have a tweet at our disposal. Why not simply do tweet.user to get the user
		            instead of following SQL. Instance variables should be created in controllers and not views. %>
		            <%# Fixed: NG %>
                <%# NOT FIXED: WA: You do not need to put a tweet.user in an instance variable. Everywhere you use
                @user, you can replace it by tweet.user %>
								<% @user = tweet.user %>
									<div class = "userTweet"><b><%= @user.fullname %></b> <span>@<%= @user.username %></span></div>
									<div><%= tweet.message %></div>
									<ul>
										<li>
                    <%# REFACTOR: WA: Move statement in if clause in User/Tweet model. Something like User#can_destroy?(tweet) %>
											<% if @user.id == current_user.id %>
												<%= link_to "Delete", tweet, confirm: "Are you sure?", method: :delete %>											
											<% else %>								
												<% if @retweet_user = tweet.find_if_retweeted(current_user.id) %>
                          <%# Use one style of hash. Either => or : %>
													<%= link_to "Retweeted", tweets_user_path(@retweet_user),  :class => 'retweeted', :title => 'Undo Retweet', method: :delete %>
												<% else %>
													<%= link_to "Retweet", {}, :class => 'retweet', :href => "#",  :title => 'Retweet' %>
												<% end %>
											<% end %>
											<div class = "retweetForm">
												<div><h2>Retweet this to your followers?</h2></div>
		                    <%# FIXME: WA: Following is bad HTML %>
		                    <%# this i used just to manage design part %>
                        <%# REFACTOR: WA: Remove spaces between = sign and attribute names and values. %>
												<div class= content>
													<div class = "userTweet"><b><%= @user.fullname %></b> <span>@<%= @user.username %></span></div>
													<div><%= tweet.message %></div>
												</div>
												<div>
													<%= form_for @tweet_user do |f| %>
														<%= f.hidden_field :tweet_id, :value => tweet.id %>
														<table>
															<tr>
																<td><%= f.submit "Cancel", :type => 'button' %></td>
																<td><%= f.submit ("Retweet") %></td>
													 		</tr>
													 	</table>
													<% end %>							
												</div>
											</div>
										</li>
									</ul>
							</td>
						</tr>						
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

twitter/app/views/tweets/mine.html.erb
<div class = "myTweetWrapper">
	<div class = "myTweetcontent">
		<div class = "myTweetBackground">
			<div class = "dashboard">
				<div>
					<div><%= link_to "Home", tweets_path %></div>
				</div>
			</div>
			
			<div>
				<div class = "myTweets">
					<div class = "tweetHeader"><b><div>Tweets</div></b></div>
					<% my_tweets.each do |tweet| %>
						<div class = "tweet">
							<% @user = tweet.user %>
							<div class = "userTweet"><b><%= @user.fullname %></b> <span>@<%= @user.username %></span></div>
							<div><%= tweet.message %></div>
							
							<% if current_user.id != @user.id %>
								<div class = "userTweet"><span>Retweeted by <%= current_user.fullname %></span></div>
							<% else %>
								<div><%= link_to 'Delete', tweet, confirm: "Are you Sure", method: :delete %></div>
							<% end %>
						</div>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>